### Machine Learning  (Background): Gram-Schmidt process
$\mathbf{u_k}\leftarrow \mathbf{v_k}-\sum_{j=1}^{k-1} proj_{\mathbf{u}_j}(\mathbf{v_k})$
<br>$, proj_{\mathbf{u}_j}(\mathbf{v_k})=\frac{< \mathbf{v}_k,\mathbf{u}_j>}
{< \mathbf{u}_j,\mathbf{u}_j>}\mathbf{u}_j$
###### by Hamed Shah-Hosseini
Explanation at: https://www.pinterest.com/HamedShahHosseini/Machine-Learning/Background-Knowledge
<br>Explanation in Persian: https://www.instagram.com/words.persian
<br>Code that: https://github.com/ostad-ai/Machine-Learning

In [51]:
# importing the required module
# درون‌بَری سنجانه نیازداشته
import numpy as np

In [39]:
# this modified method can have smaller rounding errors
# این روش سنجیده‌سازی شده، میتواند دارای ایرَنگ‌های گِرد کردن کوچکتری باشد
def modified_gram_schmidt(A,normalize=False): # row vectors
    A=A.astype('float32')
    n=A.shape[0] # no. of rows
    for j in range(n):
        for k in range(j):
            A[j]-=np.dot(A[j],A[k])/np.dot(A[k],A[k])*A[k]
    if normalize:
        for j in range(n):
            A[j]/=np.linalg.norm(A[j])
    return A

In [40]:
# The classical method which may have large rounding errors
# روش سَررَده‌ای که میتواند دارای ایرَنگ‌های گِرد کردن بزرگ باشد
def gram_schmidt(A,normalize=False):# row vectors
    A=A.astype('float32')
    n=A.shape[0] # no. of rows
    temprow=np.zeros(A.shape[1])
    for j in range(n):
        temprow.fill(0)
        for k in range(j):
            temprow+=np.dot(A[j],A[k])/np.dot(A[k],A[k])*A[k]
        A[j]-=temprow
    if normalize:
        for j in range(n):
            A[j]/=np.linalg.norm(A[j])
    return A

In [50]:
# example, rows of matrix are vectors
# نمونه، رجهای ماتکدان، بُردارها هستند
A=np.array([[1,0,1,0],[1,1,1,1],[0,1,2,1]]) 
print('Classical method:\n',gram_schmidt(A))
print('Modified method:\n',modified_gram_schmidt(A))

Classical method:
 [[ 1.  0.  1.  0.]
 [ 0.  1.  0.  1.]
 [-1.  0.  1.  0.]]
Modified method:
 [[ 1.  0.  1.  0.]
 [ 0.  1.  0.  1.]
 [-1.  0.  1.  0.]]


Hint: You can check that the processed vectors are orthogonal.<br>
نکته: میتوانید چک کنید که بُردارهای پردازش شده، فرکنجی هستند