### Machine Learning (Background): Inner products
$\mathbf{u}\cdot\mathbf{v}=\sum_{i=1}^n u_i v_i \,\rightarrow \lVert \mathbf{u} \rVert_{canonical}=\sqrt{\mathbf{u}\cdot\mathbf{u}}$ <br>
$<A,B>_F=tr(A^HB) \, \rightarrow\lVert A \rVert_F=\sqrt{<A,A>_F}$
###### by Hamed Shah-Hosseini
Explanation at: https://www.pinterest.com/HamedShahHosseini/Machine-Learning/Background-Knowledge
<br>Explanation in Persian: https://www.instagram.com/words.persian
<br>Code that: https://github.com/ostad-ai/Machine-Learning

In [98]:
# importing the required module
# درون‌بَری سنجانه نیازداشته
import numpy as np

In [99]:
# dot product and p-norms, example
# فرآورد خجک و پ-هنجارها: نمونه
vec1=np.random.randint(1,5,4)
vec2=np.random.randint(1,5,4)
print('vector 1:',vec1)
print('vector 2:',vec2)
print('dot product: ',np.dot(vec1,vec2))
print('1-norm of vector 1:',np.linalg.norm(vec1,ord=1))
print('1-norm of vector 2',np.linalg.norm(vec2,ord=1))
print('2-norm of vector 1:',np.linalg.norm(vec1,ord=2))
print('2-norm of vector 2',np.linalg.norm(vec2,ord=2))
print('canonical norm of vector 1:',np.sqrt(np.dot(vec1,vec1)))
print('canonical norm of vector 2',np.sqrt(np.dot(vec2,vec2)))

vector 1: [2 1 1 3]
vector 2: [1 2 4 3]
dot product:  17
1-norm of vector 1: 7.0
1-norm of vector 2 10.0
2-norm of vector 1: 3.872983346207417
2-norm of vector 2 5.477225575051661
canonical norm of vector 1: 3.872983346207417
canonical norm of vector 2 5.477225575051661


In [102]:
# Example for trace, determinant, and norm of a matrix
# نمونه برای رآس، بَریهنده، و هنجار یک ماتکدان
M=np.random.randint(1,5,(3,3))
eigs=np.linalg.eigvals(M)
detM=np.linalg.det(M)
print('The matrix:\n',M)
print('---------------------')
print('Eigenvalues of matrix:',eigs)
print('Trace of matrix:',np.trace(M))
print('sum of eigenvalues:',np.sum(eigs))
print('-------------')
print('Determinant of matrix: ',detM)
print('Product of eigenvalues: ',np.prod(eigs))
print('------------------')
print('Frobenius norm of matrix:',np.linalg.norm(M,ord='fro'))
print('Norm using Frobenius inner product:',np.sqrt(np.trace(M.T@M)))

The matrix:
 [[3 2 2]
 [3 1 4]
 [1 3 2]]
---------------------
Eigenvalues of matrix: [ 6.92434399  1.21506597 -2.13940996]
Trace of matrix: 6
sum of eigenvalues: 5.999999999999998
-------------
Determinant of matrix:  -18.000000000000004
Product of eigenvalues:  -18.0
------------------
Frobenius norm of matrix: 7.54983443527075
Norm using Frobenius inner product: 7.54983443527075
